### ISSUE TITLE
Adding parallelization to run tests on Cypress but have several test execution issues created

### ISSUE THREAD

**Issue by ethoreau** [Qytera-Gmbh/cypress-xray-plugin#402]
Hi,

Recently, I tried to add parallelization when executing tests with a Gitlab pipeline like that : 

```
tnr-sandbox:
   image: cypress/browsers:node-22.11.0-chrome-130.0.6723.116-1-ff-132.0.1-edge-130.0.2849.68-1
   stage: test
   parallel: 3
   rules:
       - if: $TEST == 'tnr-sandbox'
   script:
       # install dependencies
       - npm ci
       # run Cypress tests
       # - npx cypress run --parallel --browser chrome --config-file cypress-sandbox.config.js --spec "cypress/e2e/**/*" --reporter mocha-junit-reporter 
```

I have 7 tests to run, they run well with parallelization but there are several test execution issues created through the execution while when the tests run without parallelization I have only one test execution issue created.

So, I would like to know if I misconfigured the plugin, or if the adding of parallelization is not handled. 

Maybe someone already managed parallelization with creation of one test execution issue ?

FYI : I'm using the last version of the plugin (7.4.1) and the last version of Cypress (13.15.2)

Thanks
Emilie
